### ISSUE TITLE
Thermaltake Toughpower iRGB PLUS 1200W Platinum - TT Premium Edition

### ISSUE THREAD

**Issue by bl4kh4k** [chestm007/linux_thermaltake_riing#8]
Just installed your software... the 2 200mm fans in the front of the case look great now that they are not rainbows.

I do however have a Thermaltake Toughpower iRGB PLUS 1200W Platinum - TT Premium Edition

I don't see it listed as a compatible model.
[](https://www.thermaltake.com/Power_Supply/Toughpower_iRGB_Series_/Toughpower_iRGB_PLUS/C_00003142/Toughpower_iRGB_PLUS_1200W_Platinum_TT_Premium_Edition/design.htm)

I know its Christmas eve so no rush ;)

Cheers.

**Comment by chestm007** [comment]
Hi,

Currently not supported but im more then happy to implement it if your willing to be the test pilot :)

Does the PSU connect to a controller like the fans, or does it connect directly via usb?

**Comment by bl4kh4k** [comment]
I'm happy to be your test pilot!

The PSU connects directly to the USB header on the board. Does not support the fan controllers. From what i can tell they use a completely different program on Windows to control it along with power supply information (which I don't care too much about).

Its also a mini usb into the power supply which i don't believe helps in any way but thought i would mention it.

**Comment by chestm007** [comment]
Alright sweet, lets start with some basic info gathering

I'm assuming your running linux so, with the PSU connected to the USB header, do you mind giving me the output of the following command:

```
$ lsusb -v
```

also I'm guessing that you have one usb controller running the fans?

**Comment by bl4kh4k** [comment]
That is correct, fan controller on one header, power supply on another header.
[lsusb.txt](https://github.com/chestm007/linux_thermaltake_riing/files/2724485/lsusb.txt)

**Comment by bl4kh4k** [comment]
Sounds good.... I'll test it this evening. I'm perfectly comfortable setting up a vm with usb packet sniffing if first attempt fails :)

**Comment by bl4kh4k** [comment]
I'll be setting up a VM for you to work with. Doesn't appear to of worked and journalctl didn't log anything but the timestamp of the service being started. Looked at a few of the python files and looks like its outputting to stream. I don't work with python so i'm a bit limited there, assuming it should output to system.

**Comment by chestm007** [comment]
yeah i didn't think there was a high chance of it working - was just worth a shot as most of that code will be necessary in the end anyway.

If you can get me a packet capture of a few connection/disconnections and applying some fan / lighting configurations and anything else you have time for i should be able to figure this out.

**Comment by chestm007** [comment]
thanks!

I've got as far as i need too to implement a POC to verify what i currently think might be the protocol as explained below

```
    possible protocol definition:
        v--30 set/31 get ? wtf does 'fe' mean then???
        |  v--device? (42 appears to be fan LED's)
        |  |  v--lighting mode? (18 aligns with the riing protocol for per led lighting)
        |  |  |  v--possibly command variables similar too riing?
        |  |  |  |  v--parameters
        |  |  |  |  |
        30 42 18 00 ff 00 00 ...
```

as you can probably tell im not 100% sure but based on what i saw in the packet captures i should possibly be able to get the lighting to work as a start and progress from there

I'll be pushing some new changes to the same branch in the next few hours

**Comment by chestm007** [comment]
ok, those changes are now pushed, you will need to modify your config slightly.
Instead of listing the PSU in the controllers section of the config - you will need to list it as its own section `psus`

the config in `linux_thermaltake_rgb/assets/config.yml` shows what i mean right at the bottom.

if what I've done works, the psu should be illuminated the same as the rest of your fans
please try initially using the `perled` lighting configuration

if you have failures please turn on debug logging and run the daemon in the foreground in a terminal

```
DEBUG=true linux-thermaltake-rgb
```

and post the entire output displayed until it becomes repetitive (around 10 seconds or less)

**Comment by bl4kh4k** [comment]
Where should I be adding the debug line?

**Comment by chestm007** [comment]
i think I've found my mistake, theres a little bit of python black magic that goes into creating the right class for each device, more or less an autoloading factory method.
It looks like i forgot to import the PSU class :man_facepalming: 
I've updated the code, and pushed my changes - I've also added alot more debug logging as it may be useful as well.

If you wouldn't mind testing again and posting the debug logs if it once again fails to work that'd be awesome.

pretty much just execute this line in a terminal

```
DEBUG=true linux-thermaltake-rgb
```

**Comment by bl4kh4k** [comment]
[debug.log](https://github.com/chestm007/linux_thermaltake_riing/files/2747140/debug.log)

Still doesn't look like psu is read.

All I did was pip3 uninstall... then pip3 install... shouldn't make a difference?

**Comment by chestm007** [comment]
Thats missing a whole lot of the extra logging...

> All I did was pip3 uninstall... then pip3 install... shouldn't make a difference?

if thats from the packages on pypi it wont be getting my latest changes, you'll have to clone this repository, check out the `irgb-plus` branch, and pip3 install from inside that directory

**Comment by bl4kh4k** [comment]
[debug.log](https://github.com/chestm007/linux_thermaltake_riing/files/2753385/debug.log)

There we go. Did a search for any missing thermaltake files removed them manually after the uninstall... and redownloaded to a different location incase something was going wrong there but we have new logs now!

**Comment by chestm007** [comment]
the code looks right to me, It appears i havent updated the udev rule in this branch either.

can you add the following line too `/etc/udev/rules.d/90-linux_thermaltake_rgb.rules`

```
ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="264a", ATTRS{idProduct}=="2329", MODE="660", GROUP="plugdev"
```

then reboot to ensure the rule takes effect, and attempt to run the controller again?

**Comment by chestm007** [comment]
That's really strange. I'm going to give up trying to do this remotely as its obviously a bit more involved then i first thought - one of these PSU's is on my shopping list very soon so unless someone picks it up before then i'll Work on implementing this then - I'm sorry for the inconvenience...

**Comment by devcompl** [comment]
I dont have much to input but from what I've gathered [0xfe, 0x31] is controller init. So you should override ```init_controller``` in ```ThermaltakeiRGBPLUSControllerDriver```.

Also it seems to return psu P/N. If you convert ```54 50 49 2d 31 32 30 30 46 32 46 44 50 00``` in dps_protocol.txt to ASCI you get "TPI-1200F2FDP".

This should be easy to implement since it seems like they just added a Riing Plus fan to a psu. The commands should be very similar if not the same. I would start by creating a super simple script that just tries to initialize the psu controller and maybe get its version by [0x33, 0x50].

**Comment by devcompl** [comment]
Ok I got almost everything.

>https://github.com/devcompl/riingplusapi/blob/93795bc42ebd534c272f3dfda0c8643379ab8d41/riingplusapi/riingplusapi.cpp#L18-L40
```
	// vid: 0x264a pid: 0x2329
	// 0xfe, 0x31 // init, returns model
	//
	// 0x30, 0x42, mode, colors // set rgb
	// 0x30, 0x41, 0x01 // set fan silent
	// 0x30, 0x41, 0x02 // set fan performance
	// 0x30, 0x41, 0x03 // set fan off
	// 0x30, 0x41, 0x04, speed // set fan speed
	//
	// 0x30, 0x43, 0x01 // ???
	//
	// 0x31, 0x33 // WATTS?
	// 0x31, 0x34 // VVOut12
	// 0x31, 0x35 // VVout5
	// 0x31, 0x36 // VVOut33
	// 0x31, 0x37 // VIOut12
	// 0x31, 0x38 // VIOut5
	// 0x31, 0x39 // VIOut33
	// 0x31, 0x3a // Temp
	// 0x31, 0x3b // FanSpeed
	// 0x31, 0x3d // Model
	// 0x31, 0x3f // Serial Number
	// 0x31, 0x41 // ???
```

Now its only matter of getting the hid device and writing correct stuff.

**Comment by chestm007** [comment]
@devcompl looks like the data i was sending in `init_controller` was wrong :man_facepalming: 
I might throw together a really quick dummy script to just double check.

**Comment by chestm007** [comment]
@bl4kh4k if your still interested, please pull the latest changes from the `irgb-plus` branch and run `python3 tests/scripts/toughpower.py` - you may have to adjust that path depending what directory you are in, its relative to the root of the repository.

If it works, it should set your led's to a random colour on the PSU
